### ISSUE TITLE
has leaked ServiceConnection问题

### ISSUE THREAD

**Issue by graham-lemon** [taptap/TapSDK-Android#20]
## 导包
正常导入依赖包
## 接入
- onCreate方法中调用`TapLoginHelper.init(MainActivity.this, "xxx");`
- 登录按钮调用：
``` java
TapLoginHelper.registerLoginCallback(new TapLoginHelper.TapLoginResultCallback() {
                @Override
                public void onLoginSuccess(AccessToken token) {
                    ToastUtil.show("TapTap authorization succeed");
                    // 开发者调用 TapLoginHelper.getCurrentProfile() 可以获得当前用户的一些基本信息，例如名称、头像。
                    Profile profile = TapLoginHelper.getCurrentProfile();
                    String uid = profile.getUnionid();
                    // 调用第三方登录接口
                    UserManager.getInstance().saveCurrentUserId(uid);
                    LemonJamSDK.SDKCallback().onResult(PHONE_LOGIN_SUCCESS, "");
                }

                @Override
                public void onLoginCancel() {
                    Log.d("", "TapTap authorization cancelled");
                }

                @Override
                public void onLoginError(AccountGlobalError globalError) {
                    Log.d("", "TapTap authorization failed. cause: " + globalError.getMessage());
                }
            });
            // 登录
            TapLoginHelper.startTapLogin(MainActivity.this, TapLoginHelper.SCOPE_PUBLIC_PROFILE);
```
## 报错
```
W/jam.lemonjamsd: Accessing hidden field Landroid/view/inputmethod/InputMethodManager;->mCurRootView:Landroid/view/View; (light greylist, reflection)
W/jam.lemonjamsd: Accessing hidden field Landroid/view/inputmethod/InputMethodManager;->mServedView:Landroid/view/View; (light greylist, reflection)
    Accessing hidden field Landroid/view/inputmethod/InputMethodManager;->mNextServedView:Landroid/view/View; (light greylist, reflection)
D/ActivityThread: Remove activity client record, r= ActivityRecord{845b318 token=android.os.BinderProxy@f015d32 {com.lemonjam.lemonjamsdk/com.taptap.sdk.ui.TapTapActivity}} token= android.os.BinderProxy@f015d32
E/ActivityThread: Activity com.taptap.sdk.ui.TapTapActivity has leaked ServiceConnection com.taptap.sdk.ui.g$b@7b656fb that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.taptap.sdk.ui.TapTapActivity has leaked ServiceConnection com.taptap.sdk.ui.g$b@7b656fb that was originally bound here
        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1804)
        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1695)
        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1892)
        at android.app.ContextImpl.bindService(ContextImpl.java:1845)
        at android.content.ContextWrapper.bindService(ContextWrapper.java:698)
        at com.taptap.sdk.ui.g.a(CloudGameHandler.java:74)
        at com.taptap.sdk.ui.k.b(LoginClient.java:5)
        at com.taptap.sdk.ui.j.a(LoginBlock.java:5)
        at com.taptap.sdk.ui.d.a(Block.java:6)
        at com.taptap.sdk.ui.f.a(BlockManager.java:10)
        at com.taptap.sdk.ui.f.a(BlockManager.java:5)
        at com.taptap.sdk.ui.TapTapActivity.onCreate(TapTapActivity.java:24)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

请问下是哪里还需要配置？

**Comment by Luoweihong** [comment]
解决了么

**Comment by Luoweihong** [comment]
@graham-lemon

**Comment by kelv1nq1an** [comment]
抱歉才看到这个问题，我们会在下个版本里解决这个 bug。

**Comment by kelv1nq1an** [comment]
https://github.com/taptap/TapSDK-Android/releases/tag/v3.6.1 这个版本里已经修复改问题了哦。
