### ISSUE TITLE
taptap崩溃报错

### ISSUE THREAD

**Issue by Ceyase** [taptap/TapSDK-Android#32]
在登录时返回错误信息：InvalidArgument: package
而后Taptap客户端报错：
```
02-21 13:37:54.387  5894  5894 E AndroidRuntime: Process: com.taptap:channel, PID: 5894
02-21 13:37:54.387  5894  5894 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void com.taptap.common.net.v3.TapApiHook.interceptError(boolean, java.lang.Throwable, java.lang.String)' on a null object reference
02-21 13:37:54.387  5894  5894 E AndroidRuntime: 	at com.taptap.common.net.v3.ApiManager$2$1.lambda$call$0(ApiManager.java:218)
02-21 13:37:54.387  5894  5894 E AndroidRuntime: 	at com.taptap.common.net.v3.ApiManager$2$1$$ExternalSyntheticLambda0.run(Unknown Source:6)
02-21 13:37:54.387  5894  5894 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
02-21 13:37:54.387  5894  5894 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-21 13:37:54.387  5894  5894 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
02-21 13:37:54.387  5894  5894 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6825)
02-21 13:37:54.387  5894  5894 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-21 13:37:54.387  5894  5894 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-21 13:37:54.387  5894  5894 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
```
使用Webview登录则没有以上问题。

**Comment by Ceyase** [comment]
是证书MD5获取的问题，使用TDS签名工具获取的MD5和使用`keytool -exportcert -alias {alias} -keystore {storefile} | openssl dgst -md5`获取的MD5不一致。这个issue可以结束了。
